version: '3'

services: 
  app:
    image: docker.io/ossuchas/djangoapi:v1.0.0
    build:
        context: .
        dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - "8000:8000"
    expose:
      - "8000"
